/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mashinno_glasuwane;

/**
 *
 * @author blago
 */
public class Vid_glasuwane extends javax.swing.JFrame {

    /**
     * Creates new form Vid_glasuwane
     */
    public Vid_glasuwane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obshtSuvetnici_checkBox = new javax.swing.JCheckBox();
        kmetObshtina_checkBox = new javax.swing.JCheckBox();
        kmetraion_checkBox = new javax.swing.JCheckBox();
        potwurvdawam_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        izberiVsichki_checkBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        raion_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        obshtSuvetnici_checkBox.setText("Избори за общински съветници");
        obshtSuvetnici_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obshtSuvetnici_checkBoxActionPerformed(evt);
            }
        });

        kmetObshtina_checkBox.setText("Избори за кмет на община");

        kmetraion_checkBox.setText("Избори за кмет на район");
        kmetraion_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmetraion_checkBoxActionPerformed(evt);
            }
        });

        potwurvdawam_btn.setText("Потвърждавам");
        potwurvdawam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potwurvdawam_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Моля посочете в кои избори ще гласувате");

        izberiVsichki_checkBox.setText("Избери всички");
        izberiVsichki_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izberiVsichki_checkBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Район");

        raion_lbl.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(potwurvdawam_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(obshtSuvetnici_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addComponent(kmetObshtina_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kmetraion_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(raion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(izberiVsichki_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(raion_lbl))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(izberiVsichki_checkBox)
                .addGap(18, 18, 18)
                .addComponent(obshtSuvetnici_checkBox)
                .addGap(18, 18, 18)
                .addComponent(kmetObshtina_checkBox)
                .addGap(18, 18, 18)
                .addComponent(kmetraion_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(potwurvdawam_btn)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izberiVsichki_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izberiVsichki_checkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izberiVsichki_checkBoxActionPerformed

    private void obshtSuvetnici_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obshtSuvetnici_checkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obshtSuvetnici_checkBoxActionPerformed

    private void kmetraion_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmetraion_checkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmetraion_checkBoxActionPerformed

    private void potwurvdawam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potwurvdawam_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potwurvdawam_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vid_glasuwane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vid_glasuwane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vid_glasuwane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vid_glasuwane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vid_glasuwane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox izberiVsichki_checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox kmetObshtina_checkBox;
    private javax.swing.JCheckBox kmetraion_checkBox;
    private javax.swing.JCheckBox obshtSuvetnici_checkBox;
    private javax.swing.JButton potwurvdawam_btn;
    private javax.swing.JLabel raion_lbl;
    // End of variables declaration//GEN-END:variables
}
